<option value="parquet" selected>Паркет</option>
<option value="custom_wood">Паркет1</option>
<option value="timber2">Паркет2</option>
<option value="timber3">Паркет3</option>
<option value="timber4">Паркет4</option>
<option value="timber5">Паркет5</option>
<option value="stone">Мрамор</option>
<option value="stone2">Камень темный </option>
<option value="stone3">Камень серый</option>
<option value="stone4">Камень светлый 1</option>
<option value="stone5">Камень светлый 2</option>
<option value="stone6">Камень светлый 3</option>
<option value="stone7">Камень серый 2</option>
<option value="tiling">Плитка</option>
<option value="carpet">Ковер</option>