<option value="l-01">01 Геометрия</option>
<option value="l-02">02 Цветущая поляна</option>
<option value="l-03">03 Африканский орнамент</option>
<option value="l-04">04 Листья клена</option>
<option value="l-05">05 Грибница</option>
<option value="l-06">06 Мелкие завитки</option>
<option value="l-07">07 Жираф</option>
<option value="l-08">08 Листья</option>
<option value="l-09">09 Круги</option>
<option value="l-10">10 Решетка</option>
<option value="l-11">11 Дерево</option>
<option value="l-12">12 Каменный цветок</option>
<option value="l-13">13 Крупные завитки</option>