<option value="не указано">не указано</option>
<option value="сосна ц/л кл.Б">сосна ц/л кл.Б</option>
<option value="сосна экстра">сосна экстра</option>
<option value="береза паркет.">береза паркет.</option>
<option value="лиственница паркет.">лиственница паркет.</option>
<option value="лиственница ц/л">лиственница ц/л</option>
<option value="дуб паркет.">дуб паркет.</option>
<option value="дуб ц/л">дуб ц/л</option>
<option value="дуб натур">дуб натур</option>
<option value="карагач натур">карагач натур</option>
