function getParamsStock() {
  return {
	  "calcVersion": "4.1",
		"angleType": "расчетные",
		"G_min": 2000,
	  "platformLength_1": 1000,
	  "marshDist": 100,
	  "platformLength_3": 1000,
	  "M": 900,
	  "nose": 20,
	  "rackSize": 80,
	  "isColumn1": false,
	  "isColumn2": false,
	  "isColumn3": false,
	  "isColumn4": false,
	  "isColumn5": false,
	  "isColumn6": false,
	  "isColumn7": false,
	  "isColumn8": false,
	  "stairAmt1": 5,
	  "h1": 180,
	  "b1": 260,
	  "a1": 280,
	  "stairAmt2": 5,
	  "h2": 150,
	  "b2": 260,
	  "a2": 280,
	  "stairAmt3": 5,
	  "h3": 200,
	  "b3": 260,
	  "a3": 280,
	  "startTreadAmt": 0,
	  "radiusFactor": 0,
	  "asymmetryFactor": 0,
	  "stepFactor": 100,
	  "radiusFactor1": 0,
	  "asymmetryFactor1": 0,
	  "stepFactor1": 100,
	  "radiusFactor2": 0,
	  "asymmetryFactor2": 0,
	  "stepFactor2": 100,
	  "fixSpacerLength1": 0,
	  "fixSpacerLength2": 0,
	  "fixAmt3": 0,
	  "fixSpacerLength3": 0,
	  "fixAmt4": 0,
	  "fixSpacerLength4": 0,
	  "fixAmt5": 0,
	  "fixSpacerLength5": 0,
	  "fixAmt6": 0,
	  "fixSpacerLength6": 0,
	  "inclinedBeamAngle": 45,
	  "platformTopColumnAmt": 0,
	  "wallDist": 10,
	  "treadThickness": 40,
	  "riserThickness": 18,
	  "stringerThickness": 40,
	  "stringerSlotsDepth": 15,
	  "carcasPartsSpacing": 0,
	  "topPltRailing_3": false,
	  "topPltRailing_4": false,
	  "topPltRailing_5": false,
	  "handrailEndHeight": 0,
	  "handrailEndLen": 100,
		"timberRackModel": "06",
		"startNewellModel": "01",
		"balDist_bal": 200,
		"timberBalModel_bal": "01",
		"timberRackModel_bal": "01",
	  "handrailHeight_bal": 940,
	  "deliveryDist": 0,
	  "handrailCutting": 0,
	  "floorAmt": 0,
	  "extraTripAmt": 0,
	  "carcasCostFactor": 1,
	  "carcasPriceFactor": 1,
	  "treadsCostFactor": 1,
	  "treadsPriceFactor": 1,
	  "railingCostFactor": 1,
	  "railingPriceFactor": 1,
	  "wrCostFactor": 1,
	  "wrPriceFactor": 1,
	  "assemblingCostFactor": 1,
	  "assemblingPriceFactor": 1,
	  "discountFactor": 30,
	  "wallLength_1": 5000,
	  "wallLength_2": 5000,
	  "wallLength_3": 5000,
	  "wallLength_4": 5000,
	  "wallHeight_1": 5000,
	  "wallHeight_2": 5000,
	  "wallHeight_3": 5000,
	  "wallHeight_4": 5000,
	  "wallPositionX_1": -2500,
	  "wallPositionX_2": -2500,
	  "wallPositionX_3": 1000,
	  "wallPositionX_4": -2500,
	  "wallPositionZ_1": 0,
	  "wallPositionZ_2": 5000,
	  "wallPositionZ_3": 0,
	  "wallPositionZ_4": 0,
	  "wallThickness_1": 150,
	  "wallThickness_2": 150,
	  "wallThickness_3": 150,
	  "wallThickness_4": 150,
	  "wallsColor": "#cccccc",
	  "floorColor": "#cccccc",
	  "floorColor2": "#cccccc",
	  "ceilColor": "#cccccc",
	  "wallLedgeAmt": "0",
	  "floorHoleWidth": 2000,
	  "floorHoleLength": 2500,
	  "floorThickness": 300,
	  "staircaseHeight": 3000,
	  "staircasePosX": 0,
	  "staircasePosY": 0,
	  "staircasePosZ": 10,
	  "beamWidth": 200,
	  "beamPosX": 0,
	  "beamPosY": 0,
	  "beamPosZ": 0,
	  "topThreadsWidth": 900,
	  "topFloorAmt": "0",
	  "banisterSectionAmt": "0",
	  "banisterPosX": 0,
	  "banisterPosZ": 0,
	  "dimAmt": "0",
	  "dimScale": "1",
	  "calcType": "timber_stock",
	  "model": "косоуры",
	  "stairModel": "Г-образная с площадкой",
	  "turnType_1": "площадка",
	  "turnType_2": "площадка",
	  "turnSide": "правое",
	  "platformTop": "нет",
	  "platformRearStringer": "нет",
	  "riserType": "есть",
	  "topStairType": "ниже",
	  "arcSide": "right",
	  "fullArcFront": "да",
	  "startTreadsTemplate": "прямые",
	  "timberPaint": "нет",
	  "stringersMaterial": "не указано",
	  "stringersColor": "не указано",
	  "treadsMaterial": "не указано",
	  "treadsColor": "не указано",
	  "risersMaterial": "не указано",
	  "risersColor": "не указано",
	  "skirtingMaterial": "не указано",
	  "skirtingColor": "не указано",
	  "newellsMaterial": "не указано",
	  "newellsColor": "не указано",
	  "timberBalMaterial": "не указано",
	  "timberBalColor": "не указано",
	  "metalBalMaterial": "не указано",
	  "metalBalColor": "не указано",
	  "handrailsMaterial": "сосна экстра",
	  "handrailsColor": "не указано",
	  "fixType1": "не указано",
	  "fixPart1": "не указано",
	  "fixSpacer1": "не указано",
	  "fixType2": "не указано",
	  "fixPart2": "не указано",
	  "fixSpacer2": "не указано",
	  "fixType3": "не указано",
	  "fixPart3": "не указано",
	  "fixSpacer3": "не указано",
	  "fixType4": "не указано",
	  "fixPart4": "не указано",
	  "fixSpacer4": "не указано",
	  "fixType5": "не указано",
	  "fixPart5": "не указано",
	  "fixSpacer5": "не указано",
	  "fixType6": "не указано",
	  "fixPart6": "не указано",
	  "fixSpacer6": "не указано",
	  "platformTopColumn": "колонны",
	  "topFlan": "нет",
	  "bottomAngleType": "уголок",
	  "skirting_1": "нет",
	  "skirting_2": "нет",
	  "skirting_3": "нет",
	  "skirting_wnd": "нет",
	  "skirting_plt": "нет",
	  "railingSide_1": "две",
	  "railingSide_2": "две",
	  "railingSide_3": "две",
	  "handrailSide_1": "нет",
	  "handrailSide_2": "нет",
	  "handrailSide_3": "нет",
	  "backRailing_1": "нет",
	  "backHandrail_1": "нет",
	  "backRailing_2": "нет",
	  "backHandrail_2": "нет",
	  "railingModel": "Деревянные балясины",
	  "handrail": "сосна",
	  "handrailProf": "40х70 гор.",
	  "handrailSlots": "да",
	  "handrailEndType": "прямые",
	  "handrailConnectionType": "прямые",
	  "handrailConnectionType_len": "с рустом",
	  "handrailEndHor": "нет",
	  "handrailColor": "не указано",
	  "sideHandrailHolders": "нержавеющие",
	  "timberBalStep": 1,
	  "timberBalType": "точеные",
	  "timberNewellType": "квадратные",
	  "timberBalTopEnd": "квадрат",
	  "timberBalBotEnd": "квадрат",
	  "banisterSize": 50,
	  "newellTopType": "плоское",
	  "banister1": "bal_9",
	  "banister2": "bal_9",
	  "glassType": "прозрачное",
	  "railingModel_bal": "Деревянные балясины",
	  "handrail_bal": "сосна",
	  "handrailProf_bal": "40х70 гор.",
	  "handrailSlots_bal": "да",
	  "handrailConnectionType_bal": "прямые",
	  "handrailColor_bal": "не указано",
	  "banisterMaterial_bal": "40х40 черн.",
	  "rackBottom_bal": "сверху с крышкой",
	  "rigelMaterial_bal": "20х20 черн.",
	  "rigelAmt_bal": 2,
	  "glassHandrail_bal": "сверху",
	  "glassFix_bal": "профиль",
	  "handrailFixType_bal": "кронштейны",
	  "glassType_bal": "прозрачное",
	  "isOrnament_bal": "нет",
	  "glassBevels_bal": "стандартная",
	  "rackTypeKovka_bal": "40х40",
	  "banister1_bal": "bal_1",
	  "banister2_bal": "bal_1",
	  "balMaterial_bal": "крашеные",
	  "laserModel_bal": 1,
	  "banisterStart": "столб",
	  "timberBalType_bal": "точеные",
	  "timberNewellType_bal": "квадратные",
	  "timberBalTopEnd_bal": "квадрат",
	  "timberBalBotEnd_bal": "квадрат",
	  "banisterSize_bal": 40,
	  "newellTopType_bal": "плоское",
	  "metalPaint_perila_bal": "как на лестнице",
	  "metalColorNumber_bal": 0,
	  "rackLenType_bal": "стандартные",
	  "delivery": "нет",
	  "isAssembling": "нет",
	  "engineer": "нет",
	  "workers": 1,
	  "needMockup": "нет",
	  "stepCutting": "нет",
	  "noLiftCare": "нет",
	  "isWelding": "не известно",
	  "isScaffolding": "не известно",
	  "isProblemCarry": "не известно",
	  "isWarmFloor": "не известно",
	  "isHeating": "не известно",
	  "paidParking": "нет",
	  "deliveryByInstallers": "нет",
	  "discountMode": "процент",
	  "wallsMat": "brick_01",
	  "floorMat": "carpet",
	  "floorMat2": "carpet",
	  "ceilMat": "painted",
	  "topThreadsType": "прямые",
	}
}