var wrTemplates = {
	'default': {
    "model_wr": "распашной",
    "wallProfX": 60,
		"geom_wr": "прямой",
		"sectDoorsModel_wr": "панель",
		"type_wr": "Отдельно стоящий",
		"leftWall_wr": "боковина",
		"rightWall_wr": "боковина",
		"topWall_wr": "накладная",
		"botWall_wr": "цоколь",
		"botWallType": "накладная панель",
		"rearWall_wr": "накладная",
		"topPanelOffset_wr": 0,
		"width_wr": 1500,
		"leftWidth": 1500,
		"rightWidth": 1500,
		"height_wr": 2000,
		"depth_wr": 600,
		"leftDept": 600,
		"rightDepth": 600,
		"leftSect": "нет",
		"leftSectWidth": 0,
		"leftSectDepth": 550,
		"leftSectShelfAmt": 5,
		"rightSect": "нет",
		"rightSectWidth": 0,
		"rightSectDepth": 550,
		"rightSectShelfAmt": 5,
		"diagDoorType": "прямая",
		"diagDoorRad": 1500,
		"topOnlay_wr": "нет",
		"sideWall_wr": "бруски+щит",
		"sectDoorsType_wr": "вкладные",
		"sectDoorsModel_wr": "составная панель",
		"rearWallMat_wr": "двп",
		"doorProfMat_wr": "C",
		"schlegel": "есть",
		"schlegelColor": "темно-серый",
		"closer": "нет",
		"carcasMat": "лдсп",
		"carcasMatColor": "не указан",
		"rearWallColor": "не указан",
		"profileColor": "не указан",
		"doorPlateColor": "не указан",
		"boxType": "метабоксы",
		"boxRailingModel": "Боярд",
		"doorsMat_wr": "щит",
		"boxHandles": "нет",
		"faceEdging": 2,
		"sideEdging": 0.4,
		"carcasThk_wr": 40,
		"contentThk_wr": 16,
		"doorPlateThk": 10,
		"rearWallThk_wr": 4,
		"rearWallDelta_wr": 2,
		"doorsThk_wr": 16,
		"boxBotThk": 16,
		"legsHeight_wr": 80,
		"doorsOffset_wr": 100,
		"isTopShelf": "нет",
		"topShelfPosY": 1800,
		"topShelfSect1": 1,
		"topShelfSect2": 2,
		"sectAmt_r": 1,
		"isTopShelf_r": "есть",
		"topShelfPosY_r": 1800,
		"topShelfSect1_r": 21,
		"boxAmt_wr": 0,
		"curSect": "все",
		"eqBorderTop": 1000,
		"eqBorderBot": 0,
		"copySectType": "та же",
		"copyType": "зазор",
		"copyMooveY": 200,
		"copySect": 1,
		"kupeDoorAmt_wr": 3,
		"isDoorsEqual": "да",
		"sectAmt": 1,
		"sections": [
		  {
			"width": 1468,
			"type": "вправо"
		  }
		],
		"boxes": []
	},
};

var wrFilling = {
    'штанга': {
        'width_wr': 800, // Относительно этого считаем наполнение
        'height_wr': 2000,
        'topShelfPosY': 1700,
        'isTopShelf': 'есть',
        'boxes': [
            {
                "sect": "1",
                "posX": 0,
                "posY": 350,
                "height": 200,
                "type": "полки",
                "widthType": "по секции",
                "width": 768,
                "boxSect": 1,
                "boxPosX": 0,
                "boxRow": 350,
                "distTop": 0,
                "distBot": 300,
                "boxWidthType": "по секции",
                "boxWidth": 768,
                "boxHeight": 200,
                "boxCarcasHeight": 120,
                "shelfSideOffset": 0,
                "itemAmt": 1,
                "borderShelfs": "нет",
                "itemsGap": 2,
                "boxHandles": "нет",
                "boxType": "полки",
                "poleStart": "нет",
                "poleEnd": "нет",
                "boxDoorPlusIn": 0,
                "boxDoorPlusRight": -2,
                "boxDoorPlusLeft": -2,
                "boxDoorPlusTop": -2,
                "boxDoorPlusBot": -2
            },
            {
                "sect": "1",
                "posX": 0,
                "posY": 1600,
                "height": 25,
                "type": "штанга",
                "widthType": "по секции",
                "width": 768,
                "boxSect": 1,
                "boxPosX": 0,
                "boxRow": 1600,
                "distTop": 0,
                "distBot": 0,
                "boxWidthType": "по секции",
                "boxWidth": 768,
                "boxHeight": 25,
                "boxCarcasHeight": 120,
                "shelfSideOffset": 0,
                "itemAmt": 1,
                "borderShelfs": "нет",
                "itemsGap": 2,
                "boxHandles": "нет",
                "boxType": "штанга",
                "poleStart": "нет",
                "poleEnd": "нет",
                "boxDoorPlusIn": 0,
                "boxDoorPlusRight": -2,
                "boxDoorPlusLeft": -2,
                "boxDoorPlusTop": -2,
                "boxDoorPlusBot": -2
            }
        ]
    },
    'штанга+полки': {
        'width_wr': 800, // Относительно этого считаем наполнение
        'height_wr': 2000,
        'topShelfPosY': 1700,
        'isTopShelf': 'есть',
        'boxes': [
            {
              "sect": "1",
              "posX": 0,
              "posY": 350,
              "height": 200,
              "type": "полки",
              "widthType": "по секции",
              "width": 768,
              "boxSect": 1,
              "boxPosX": 0,
              "boxRow": 350,
              "distTop": 0,
              "distBot": 300,
              "boxWidthType": "по секции",
              "boxWidth": 768,
              "boxHeight": 200,
              "boxCarcasHeight": 120,
              "shelfSideOffset": 0,
              "itemAmt": 1,
              "borderShelfs": "нет",
              "itemsGap": 2,
              "boxHandles": "нет",
              "boxType": "полки",
              "poleStart": "нет",
              "poleEnd": "нет",
              "boxDoorPlusIn": 0,
              "boxDoorPlusRight": -2,
              "boxDoorPlusLeft": -2,
              "boxDoorPlusTop": -2,
              "boxDoorPlusBot": -2
            },
            {
              "sect": "1",
              "posX": 400,
              "posY": 100,
              "height": 1584,
              "type": "перегородка",
              "widthType": "по секции",
              "width": 768,
              "boxSect": 1,
              "boxPosX": 400,
              "boxRow": 100,
              "distTop": 0,
              "distBot": 0,
              "boxWidthType": "по секции",
              "boxWidth": 768,
              "boxHeight": 1584,
              "boxCarcasHeight": 120,
              "shelfSideOffset": 0,
              "itemAmt": 1,
              "borderShelfs": "нет",
              "itemsGap": 2,
              "boxHandles": "нет",
              "boxType": "перегородка",
              "poleStart": "нет",
              "poleEnd": "нет",
              "boxDoorPlusIn": 0,
              "boxDoorPlusRight": -2,
              "boxDoorPlusLeft": -2,
              "boxDoorPlusTop": -2,
              "boxDoorPlusBot": -2
            },
            {
              "sect": "1",
              "posX": 0,
              "posY": 1600,
              "height": 25,
              "type": "штанга",
              "widthType": "задается",
              "width": 400,
              "boxSect": 1,
              "boxPosX": 0,
              "boxRow": 1600,
              "distTop": 0,
              "distBot": 0,
              "boxWidthType": "задается",
              "boxWidth": 400,
              "boxHeight": 25,
              "boxCarcasHeight": 120,
              "shelfSideOffset": 0,
              "itemAmt": 1,
              "borderShelfs": "нет",
              "itemsGap": 2,
              "boxHandles": "нет",
              "boxType": "штанга",
              "poleStart": "нет",
              "poleEnd": "нет",
              "boxDoorPlusIn": 0,
              "boxDoorPlusRight": -2,
              "boxDoorPlusLeft": -2,
              "boxDoorPlusTop": -2,
              "boxDoorPlusBot": -2
            },
            {
              "sect": "1",
              "posX": 416,
              "posY": 442,
              "height": 1258,
              "type": "полки",
              "widthType": "задается",
              "width": 352,
              "boxSect": 1,
              "boxPosX": 416,
              "boxRow": 442,
              "distTop": 0,
              "distBot": 0,
              "boxWidthType": "задается",
              "boxWidth": 352,
              "boxHeight": 1258,
              "boxCarcasHeight": 120,
              "shelfSideOffset": 0,
              "itemAmt": 4,
              "borderShelfs": "нет",
              "itemsGap": 2,
              "boxHandles": "нет",
              "boxType": "полки",
              "poleStart": "нет",
              "poleEnd": "нет",
              "boxDoorPlusIn": 0,
              "boxDoorPlusRight": -2,
              "boxDoorPlusLeft": -2,
              "boxDoorPlusTop": -2,
              "boxDoorPlusBot": -2
            }
        ]
    }
}